customCommands:
  - key: "<c-a>" # ctrl + a
    description: "pick AI commit"
    command: 'git commit -m "{{.Form.Msg}}"'
    context: "files"
    prompts:
      - type: "menuFromCommand"
        title: "ai Commits"
        key: "Msg"
        command: "/home/supun/.dotfiles/lazygit/.config/lazygit/generate-commit.sh"
        filter: "^(?P<raw>.+)$"
        valueFormat: "{{ .raw }}"
        labelFormat: "{{ .raw | green }}"
