########## MAIN HYPRLAND CONFIG ##########

# Source modular configs
source = ~/.config/hypr/env.conf
source = ~/.config/hypr/style.conf
source = ~/.config/hypr/wallust/wallust-hyprland.conf
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/rules.conf
source = ~/.config/hypr/workspace-rules.conf
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/autostart.conf


# General settings
general {
    gaps_in = 2
    gaps_out = 5
    border_size = 2
    layout = dwindle
}




animations {
    enabled = yes

    bezier = overshoot, 0.05, 0.9, 0.1, 1.1
    bezier = smoothOut, 0.16, 1, 0.3, 1
    bezier = smoothIn, 0.4, 0.0, 0.2, 1.0

    animation = windows, 1, 7, overshoot, popin 80%
    animation = windowsIn, 1, 7, smoothOut, popin 80%
    animation = windowsOut, 1, 5, smoothIn, popin 80%

    animation = workspaces, 0
    animation = fade, 1, 7, smoothOut
    animation = fadeIn, 1, 7, smoothOut
    animation = fadeOut, 1, 5, smoothIn

    animation = windowsMove, 0
}

