########## MAIN HYPRLAND CONFIG ##########

# Source modular configs
source = ~/.config/hypr/env.conf
source = ~/.config/hypr/style.conf
source = ~/.config/hypr/wallust/wallust-hyprland.conf
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/rules.conf
source = ~/.config/hypr/workspace-rules.conf
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/autostart.conf


# General settings
general {
    gaps_in = 2
    gaps_out = 5
    border_size = 2
    layout = dwindle
}




animations {
    enabled = no

    bezier = ultra, 0.3, 0.9, 0.4, 1.0

    animation = windows, 1, 4, ultra
    animation = windowsIn, 1, 4, ultra
    animation = windowsOut, 1, 4, ultra

    animation = workspaces, 1, 4, ultra
    animation = fade, 1, 4, default

    animation = windowsMove, 0
}

