########## STYLE ##########

# Color Palette
$bg = rgb(1e1e2e)
$fg = rgb(cdd6f4)
$accent = rgb(89b4fa)
$border = rgb(74c7ec)

general {
    col.active_border = $accent
    col.inactive_border = $bg
}


