# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #E6E7E7
background         #272626
cursor             #8C8B8A

active_tab_foreground     #272626
active_tab_background     #E6E7E7
inactive_tab_foreground   #E6E7E7
inactive_tab_background   #272626

active_border_color   #E6E7E7
inactive_border_color #272626
bell_border_color     #1E1D1C

color0      #4C4C4C
color1		#1E1D1C
color2		#252323
color3		#4D4D4C
color4		#525352
color5		#767676
color6		#8A8B8B
color7		#D3D4D4
color8		#949494
color9		#282625
color10		#312F2E
color11		#676766
color12		#6D6E6D
color13		#9E9E9E
color14		#B9B9B9
color15		#D3D4D4
