# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #FBF7ED
background         #171717
cursor             #8C8784

active_tab_foreground     #171717
active_tab_background     #FBF7ED
inactive_tab_foreground   #FBF7ED
inactive_tab_background   #171717

active_border_color   #FBF7ED
inactive_border_color #171717
bell_border_color     #131013

color0      #3E3E3E
color1		#131013
color2		#161114
color3		#441D21
color4		#441D21
color5		#856256
color6		#B6AF99
color7		#F1ECDD
color8		#A8A59B
color9		#191619
color10		#1D171A
color11		#5B272C
color12		#5B272C
color13		#B18272
color14		#F3E9CC
color15		#F1ECDD
