# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #C6E9EA
background         #000107
cursor             #739DAD

active_tab_foreground     #000107
active_tab_background     #C6E9EA
inactive_tab_foreground   #C6E9EA
inactive_tab_background   #000107

active_border_color   #C6E9EA
inactive_border_color #000107
bell_border_color     #132735

color0      #000107
color1		#132735
color2		#193E54
color3		#1C4358
color4		#2C5D69
color5		#316C77
color6		#448F93
color7		#A5D7D9
color8		#739698
color9		#193446
color10		#215270
color11		#255975
color12		#3B7C8C
color13		#428F9F
color14		#5BBFC4
color15		#A5D7D9
