unbind r
bind r source-file ~/.tmux.conf \; display-message "Config reloaded..."

set -g prefix C-s
set -g mouse on
set -g default-terminal "tmux-256color"
set-option -g status-position top
set -gq allow-passthrough on
set -g visual-activity off
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

bind-key -r f run-shell "tmux neww ~/.scripts/tmux-sessionizer"
# Set new panes to open in current directory
bind s new-window -c "#{pane_current_path}"
bind h split-window -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"
# Go to next session
bind-key n switch-client -n

# Go to previous session
bind-key p switch-client -p

# List sessions (built-in menu)
bind-key s choose-session

bind-key "C-l" run-shell -b "~/.tmux/plugins/tmux-fzf/scripts/window.sh switch"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'catppuccin/tmux#v2.1.2'
set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_status_style "rounded"


if "test ! -d ~/.tmux/plugins/tpm"\
      "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"
# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 0
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
# set -ag status-left "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_directory}"
set -ag status-right "#{E:@catppuccin_status_uptime}"
set -g @catppuccin_window_number_position "left"
set -g @catppuccin_window_text ""
set -g @catppuccin_window_current_text ""
TMUX_FZF_LAUNCH_KEY="C-z"
run '~/.tmux/plugins/tpm/tpm'

