/* wallust template - colors-hyprlock */

$rosewater = rgb({{color15 | strip}})
$rosewaterAlpha = {{color15 | strip}}

$flamingo = rgb({{color14 | strip}})
$flamingoAlpha = {{color14 | strip}}

$pink = rgb({{color13 | strip}})
$pinkAlpha = {{color13 | strip}}

$mauve = rgb({{color5 | strip}})
$mauveAlpha = {{color5 | strip}}

$red = rgb({{color1 | strip}})
$redAlpha = {{color1 | strip}}

$maroon = rgb({{color9 | strip}})
$maroonAlpha = {{color9 | strip}}

$peach = rgb({{color3 | strip}})
$peachAlpha = {{color3 | strip}}

$yellow = rgb({{color11 | strip}})
$yellowAlpha = {{color11 | strip}}

$green = rgb({{color2 | strip}})
$greenAlpha = {{color2 | strip}}

$teal = rgb({{color6 | strip}})
$tealAlpha = {{color6 | strip}}

$sky = rgb({{color12 | strip}})
$skyAlpha = {{color12 | strip}}

$sapphire = rgb({{color12 | strip}})
$sapphireAlpha = {{color12 | strip}}

$blue = rgb({{color4 | strip}})
$blueAlpha = {{color4 | strip}}

$lavender = rgb({{color5 | strip}})
$lavenderAlpha = {{color5 | strip}}

$text = rgb({{foreground | strip}})
$textAlpha = {{foreground | strip}}

$subtext1 = rgb({{color7 | strip}})
$subtext1Alpha = {{color7 | strip}}

$subtext0 = rgb({{color8 | strip}})
$subtext0Alpha = {{color8 | strip}}

$overlay2 = rgb({{color8 | strip}})
$overlay2Alpha = {{color8 | strip}}

$overlay1 = rgb({{color0 | strip}})
$overlay1Alpha = {{color0 | strip}}

$overlay0 = rgb({{color0 | strip}})
$overlay0Alpha = {{color0 | strip}}

$surface2 = rgb({{color0 | strip}})
$surface2Alpha = {{color0 | strip}}

$surface1 = rgb({{color0 | strip}})
$surface1Alpha = {{color0 | strip}}

$surface0 = rgb({{color0 | strip}})
$surface0Alpha = {{color0 | strip}}

$base = rgb({{background | strip}})
$baseAlpha = {{background | strip}}

$mantle = rgb({{color0 | strip}})
$mantleAlpha = {{color0 | strip}}

$crust = rgb({{color0 | strip}})
$crustAlpha = {{color0 | strip}}
