#!/bin/bash

session=$(tmux list-sessions -F '#S' | fzf)

if [ -n "$session" ]; then
  if [ -n "$TMUX" ]; then
    tmux switch-client -t "$session"
  else
    tmux attach-session -t "$session"
  fi
fi
