/* wallust template - colors-hyprlock */

$rosewater = rgb(AED9E6)
$rosewaterAlpha = AED9E6

$flamingo = rgb(6DC4DD)
$flamingoAlpha = 6DC4DD

$pink = rgb(5378BD)
$pinkAlpha = 5378BD

$mauve = rgb(3E5A8E)
$mauveAlpha = 3E5A8E

$red = rgb(0B0E26)
$redAlpha = 0B0E26

$maroon = rgb(0F1333)
$maroonAlpha = 0F1333

$peach = rgb(2E2A7A)
$peachAlpha = 2E2A7A

$yellow = rgb(3E38A3)
$yellowAlpha = 3E38A3

$green = rgb(0E132D)
$greenAlpha = 0E132D

$teal = rgb(5293A6)
$tealAlpha = 5293A6

$sky = rgb(3A5289)
$skyAlpha = 3A5289

$sapphire = rgb(3A5289)
$sapphireAlpha = 3A5289

$blue = rgb(2B3E67)
$blueAlpha = 2B3E67

$lavender = rgb(3E5A8E)
$lavenderAlpha = 3E5A8E

$text = rgb(CCEAF3)
$textAlpha = CCEAF3

$subtext1 = rgb(AED9E6)
$subtext1Alpha = AED9E6

$subtext0 = rgb(7998A1)
$subtext0Alpha = 7998A1

$overlay2 = rgb(7998A1)
$overlay2Alpha = 7998A1

$overlay1 = rgb(3D3C44)
$overlay1Alpha = 3D3C44

$overlay0 = rgb(3D3C44)
$overlay0Alpha = 3D3C44

$surface2 = rgb(3D3C44)
$surface2Alpha = 3D3C44

$surface1 = rgb(3D3C44)
$surface1Alpha = 3D3C44

$surface0 = rgb(3D3C44)
$surface0Alpha = 3D3C44

$base = rgb(16151C)
$baseAlpha = 16151C

$mantle = rgb(3D3C44)
$mantleAlpha = 3D3C44

$crust = rgb(3D3C44)
$crustAlpha = 3D3C44
