# $background = rgb(020202)
# $foreground = rgb(F6F8FB)
# $color0 = rgb(020202)
# $color1 = rgb(020202)
# $color2 = rgb(131A24)
# $color3 = rgb(2C3B47)
# $color4 = rgb(4A6070)
# $color5 = rgb(647C8F)
# $color6 = rgb(ABB9C5)
# $color7 = rgb(F6F8FB)
# $color8 = rgb(1D1D1D)
# $color9 = rgb(020202)
# $color10 = rgb(131A24)
# $color11 = rgb(2C3B47)
# $color12 = rgb(4A6070)
# $color13 = rgb(647C8F)
# $color14 = rgb(ABB9C5)
# $color15 = rgb(F6F8FB)



$accent = 020202
$background = 020202
$foreground = F6F8FB
$color0 = 020202
$color1 = 020202
$color2 = 131A24
$color3 = 2C3B47
$color4 = 4A6070
$color5 = 647C8F
$color6 = ABB9C5
$color7 = F6F8FB

general {
    col.active_border = rgba(647C8Fff)
    col.inactive_border = rgba(02020280)
}
