/* wallust template - colors-hyprlock */

$rosewater = rgb(D3D0D3)
$rosewaterAlpha = D3D0D3

$flamingo = rgb(B9B2B8)
$flamingoAlpha = B9B2B8

$pink = rgb(886BA1)
$pinkAlpha = 886BA1

$mauve = rgb(665079)
$mauveAlpha = 665079

$red = rgb(1A192C)
$redAlpha = 1A192C

$maroon = rgb(23223A)
$maroonAlpha = 23223A

$peach = rgb(403340)
$peachAlpha = 403340

$yellow = rgb(554456)
$yellowAlpha = 554456

$green = rgb(1F1D30)
$greenAlpha = 1F1D30

$teal = rgb(8B868A)
$tealAlpha = 8B868A

$sky = rgb(6F5987)
$skyAlpha = 6F5987

$sapphire = rgb(6F5987)
$sapphireAlpha = 6F5987

$blue = rgb(534365)
$blueAlpha = 534365

$lavender = rgb(665079)
$lavenderAlpha = 665079

$text = rgb(E6E4E6)
$textAlpha = E6E4E6

$subtext1 = rgb(D3D0D3)
$subtext1Alpha = D3D0D3

$subtext0 = rgb(949294)
$subtext0Alpha = 949294

$overlay2 = rgb(949294)
$overlay2Alpha = 949294

$overlay1 = rgb(464650)
$overlay1Alpha = 464650

$overlay0 = rgb(464650)
$overlay0Alpha = 464650

$surface2 = rgb(464650)
$surface2Alpha = 464650

$surface1 = rgb(464650)
$surface1Alpha = 464650

$surface0 = rgb(464650)
$surface0Alpha = 464650

$base = rgb(202029)
$baseAlpha = 202029

$mantle = rgb(464650)
$mantleAlpha = 464650

$crust = rgb(464650)
$crustAlpha = 464650
