/* wallust template - colors-hyprlock */

$rosewater = rgb(F3D6CF)
$rosewaterAlpha = F3D6CF

$flamingo = rgb(F8BEAF)
$flamingoAlpha = F8BEAF

$pink = rgb(F8BEAF)
$pinkAlpha = F8BEAF

$mauve = rgb(BA8F83)
$mauveAlpha = BA8F83

$red = rgb(462942)
$redAlpha = 462942

$maroon = rgb(5D3759)
$maroonAlpha = 5D3759

$peach = rgb(775060)
$peachAlpha = 775060

$yellow = rgb(9F6A80)
$yellowAlpha = 9F6A80

$green = rgb(744D5E)
$greenAlpha = 744D5E

$teal = rgb(BA8F83)
$tealAlpha = BA8F83

$sky = rgb(9F6A80)
$skyAlpha = 9F6A80

$sapphire = rgb(9F6A80)
$sapphireAlpha = 9F6A80

$blue = rgb(775060)
$blueAlpha = 775060

$lavender = rgb(BA8F83)
$lavenderAlpha = BA8F83

$text = rgb(FDE8E3)
$textAlpha = FDE8E3

$subtext1 = rgb(F3D6CF)
$subtext1Alpha = F3D6CF

$subtext0 = rgb(AA9691)
$subtext0Alpha = AA9691

$overlay2 = rgb(AA9691)
$overlay2Alpha = AA9691

$overlay1 = rgb(080007)
$overlay1Alpha = 080007

$overlay0 = rgb(080007)
$overlay0Alpha = 080007

$surface2 = rgb(080007)
$surface2Alpha = 080007

$surface1 = rgb(080007)
$surface1Alpha = 080007

$surface0 = rgb(080007)
$surface0Alpha = 080007

$base = rgb(080007)
$baseAlpha = 080007

$mantle = rgb(080007)
$mantleAlpha = 080007

$crust = rgb(080007)
$crustAlpha = 080007
