# $background = rgb(26262D)
# $foreground = rgb(FEF2DE)
# $color0 = rgb(4C4C53)
# $color1 = rgb(6E4D5C)
# $color2 = rgb(6F5155)
# $color3 = rgb(505886)
# $color4 = rgb(A9766B)
# $color5 = rgb(B27C6E)
# $color6 = rgb(BDA478)
# $color7 = rgb(F5E5C7)
# $color8 = rgb(ACA08B)
# $color9 = rgb(93677B)
# $color10 = rgb(946C71)
# $color11 = rgb(6B75B3)
# $color12 = rgb(E19D8E)
# $color13 = rgb(EEA593)
# $color14 = rgb(FCDBA0)
# $color15 = rgb(F5E5C7)



$accent = 6E4D5C
$background = 26262D
$foreground = FEF2DE
$color0 = 4C4C53
$color1 = 6E4D5C
$color2 = 6F5155
$color3 = 505886
$color4 = A9766B
$color5 = B27C6E
$color6 = BDA478
$color7 = F5E5C7

general {
    col.active_border = rgba(B27C6Eff)
    col.inactive_border = rgba(4C4C5380)
}
