# $background = rgb(111014)
# $foreground = rgb(CCF0FA)
# $color0 = rgb(39393C)
# $color1 = rgb(100C17)
# $color2 = rgb(441B2F)
# $color3 = rgb(481D31)
# $color4 = rgb(1E5085)
# $color5 = rgb(963B3A)
# $color6 = rgb(519EB4)
# $color7 = rgb(ADE1EF)
# $color8 = rgb(799DA7)
# $color9 = rgb(16101F)
# $color10 = rgb(5B253F)
# $color11 = rgb(602641)
# $color12 = rgb(286AB1)
# $color13 = rgb(C84E4E)
# $color14 = rgb(6CD3F0)
# $color15 = rgb(ADE1EF)



$accent = 100C17
$background = 111014
$foreground = CCF0FA
$color0 = 39393C
$color1 = 100C17
$color2 = 441B2F
$color3 = 481D31
$color4 = 1E5085
$color5 = 963B3A
$color6 = 519EB4
$color7 = ADE1EF

general {
    col.active_border = rgba(963B3Aff)
    col.inactive_border = rgba(39393C80)
}
